Bugfixes in cinema code

diff --git a/gsas_prepare_cinema b/gsas_prepare_cinema
--- a/gsas_prepare_cinema
+++ b/gsas_prepare_cinema
@@ -1,8 +1,6 @@
 # #!/bin/bash
 # conditions for this to work:
 # - PNAM entries/phase names have to be defined in input phase files
-# - PNAM entries must be unique
-# - refinements should have converged
 
 # remove previous files
 rm phase_list.txt
@@ -30,8 +28,9 @@ for file in `ls -1rt *.PVE`; do
     # get the phase name and get rid of spaces
     name=`grep PNAM $expfile | grep "CRS$phase"`
     name=${name:14:60}
-    name=`echo $name | sed 's/[ ,.\/\\]//g'`
+    name=`echo $name | sed 's/[\/\\. ;?\r]//g'`
     echo "    - phase name is <$name>"
+#     read -p "wait..."
     
     # is there a phase name?
     if [ ${#name} -eq 0 ]; then
@@ -44,8 +43,7 @@ for file in `ls -1rt *.PVE`; do
     echo "{print \$1,\",\",\$2}" > awk_temp2.awk
     grep "\"$phase " $file | awk -f awk_temp.awk -F'\" ' 2>/dev/null | awk -f awk_temp2.awk > ${file:0:${#file}-4}_$name.csv
     echo "    - output PVE values to <${file:0:${#file}-4}_$name.csv>"
-
-	# read -p "Wait after filename...."
+    
     # check if the phase name is already listed in the phase list
     grep $name phase_list.txt > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
@@ -71,12 +69,6 @@ rm cinema_data.csv 2>/dev/null
 
 # check if we have extra data
 if [ "$1" != "" ]; then
-  # convert to unix format, just in case someone uses Windows...
-  dos2unix $1
-  if [ $? -eq 127 ]; then
-    echo "dos2unix not found - if no files from a Windows machine are involved, you may continue."
-    read -p "...otherwise, please Ctrl-c and install dos2unix."
-  fi
   let extra_data_cols=`awk -F ',' '{ print NF; exit;}' $1`
   # first column has to be analysis run
   let "extra_data_cols -= 1"
@@ -132,26 +124,27 @@ echo "" >> cinema_data.csv
 # loop through all PVE files/analysis runs
 for file in `ls -1rt *.PVE`; do
   expfile=${file:0:${#file}-4}
-  echo -e "\n\n\nAdding data for $expfile (columns with extra data: <$extra_data_cols>..."
+  echo "Adding data for $expfile..."
   # check if we have extra data
-  if [ "$extra_data_cols" != "0" ]; then
+  if [ $extra_data_cols -gt 0 ]; then
     # find the line with the analysis file, search only in the first column
-    cut -f1 -d',' $1 | grep -i -n $expfile | cut -f1 -d':' > temp.txt 
+    cut -f1 -d',' $1 | grep -n $expfile | cut -f1 -d':' > temp.txt 
     if [ -s temp.txt ]; then
-      echo "  - Found extra data in $1"
+      echo " - Found extra data in $1"
       head -n `cat temp.txt` $1 | tail -n 1 | tr "\n" "," >> cinema_data.csv
     else
-      echo "  - Found no extra data in $1"
+      echo " - Found no extra data in $1"
       echo -n "$expfile,`cat temp_extra_data.txt`">> cinema_data.csv
     fi
   else
-    # no exra data
+    # no extra data
     echo -n "$expfile,">> cinema_data.csv
   fi
 #   read -p "wait after extra data"
 
   # add the CHISQ, need to get it from LST files
   grep Reduced $expfile.LST | tail -n 1 | awk '{ if($4=="nan" || $4=="-nan"){print "NaN";}else{print $4;} }' |  tr "\n" "," >> cinema_data.csv
+  echo " - Added CHISQ"
   
   # loop through all phases, either add data or blanks
   for phase in `cat phase_list.txt`; do
@@ -162,7 +155,7 @@ for file in `ls -1rt *.PVE`; do
 #     echo "Field: <$field>"
     if [ -e `cat temp.txt` ]; then
       # we have a file - let's transpose and add
-      echo "  - adding phase $phase from `cat temp.txt`..."
+      echo " - adding phase $phase from `cat temp.txt`..."
       # go through each field in the longest file for that phase and see if we have it in the current one
       for field in `cut -f1 -d',' temp_max_$phase.txt`; do
 #  	echo "    - checking field <$field>..."
@@ -188,24 +181,15 @@ for file in `ls -1rt *.PVE`; do
   
   # check if we have a folder for images
   if [ -d "images" ]; then
-    echo "  - image folder exists"
+    echo " - image folder exists"
   else
-    echo "  - creating folder for images"
+    echo " - creating folder for images"
     mkdir images
   fi
   
   # generate graphic
-  echo $expfile > GSAS_EXP
-  echo "k l l c" > temp.txt
-  echo "2" >> temp.txt
-  echo "x" >> temp.txt
-  echo "x" >> temp.txt
-  echo "x" >> temp.txt
-#   expedt `cat GSAS_EXP`.EXP < temp.txt > output.txt
-#   powpref $expfile > output.txt
-#   genles $expfile > output.txt
   let bank=2
-  echo "  - Generating plot of histogram <$bank> for analysis <$expfile>..."
+  echo " - Generating plot of histogram <$bank> for analysis <$expfile>..."
   echo "z e" > input.txt
   echo "i b m d t" >> input.txt
   # select histogram 2 #### THIS IS WHERE WE SELECT ANOTHER HISTOGRAM FOR PLOTTING! #####
@@ -213,17 +197,30 @@ for file in `ls -1rt *.PVE`; do
   # plot
   echo "p" >> input.txt
   # title
-  echo "TEMP" >> input.txt
+  echo "temp" >> input.txt
   # filename
-  echo "TEMP" >> input.txt
+  echo "temp" >> input.txt
   # empty line
   echo " " >> input.txt
   # get out
   echo "x" >> input.txt
   # run the thing
-#   powplot $expfile < input.txt > output.txt
-  # convert EPS to png and delete original file
-#   convert -density 300 TEMP.EPS images/$expfile-B$bank.png 
+  powpref $expfile > output.txt
+  genles $expfile > output.txt
+  powplot $expfile < input.txt > output.txt
+  
+  # test if convert is ImageMagick
+  convert -version | grep ImageMagick > /dev/null
+  if [ $? -eq 0 ]; then
+    # convert EPS to png and delete original file
+    echo " - ImageMagick found - converting EPS to PNG..."
+    convert -density 300 temp.EPS images/$expfile-B$bank.png 
+  else
+    echo "ImageMagick convert command not found or not in the primary search path!"
+    echo "Cannot convert EPS file to PNG, please abort and "
+    read -p "install ImageMagick and make sure it's found when <convert> is issued."
+  fi
+  rm temp.EPS 
   
   # add the file to the output CSV, no comma since this is the last entry
   echo -n " images/$expfile-B2.png " >> cinema_data.csv
@@ -231,7 +228,9 @@ for file in `ls -1rt *.PVE`; do
   # Was a phase fraction refined? If so we need to add it to the new PVE file
   grep "PHFR" $expfile.PVE > temp.txt
   if [ $? -eq 0 ]; then
-    # phase scale was refined, let's add the weight fraction (need to do error bars on another day...
+    echo $expfile > GSAS_EXP
+    # phase scale was refined, let's add the weight fraction (need to do 
+    # error bars on another day...
     for ((phase=1;phase<=`gsas_get_number_of_phases`;phase++)); do
       wtfrac=`gsas_get_current_wtfrac $phase`
       wtfrac_esd=`gsas_get_current_wtfrac_esd $phase`
@@ -253,8 +252,6 @@ echo "Deleting unwanted columns..."
 echo "_RM" > cinema_exclude.txt
 # don't want PHFR as we compute the WTFR
 echo "PHFR" >> cinema_exclude.txt
-# don't want symmetry-equivalent parameters
-echo -e "\*" >> cinema_exclude.txt
 for column in  `cat cinema_exclude.txt`; do
   echo "Searching for <$column> in cinema_data.csv..."
   grep $column cinema_data.csv >> /dev/null
@@ -272,6 +269,8 @@ for column in  `cat cinema_exclude.txt`; do
     grep $column cinema_data.csv > /dev/null
   done
 done
+# get rid of spaces after commas to avoid confusing the import
+sed -i "s/, \+/,/g" cinema_data.csv 
 
 # remove the last column
 # awk -F ',' -v OFS=, '{ for (i=1;i<=NF-2;i++){ printf $i"," }; printf $i; printf "\n" } ' < cinema_data.csv > temp.txt
@@ -291,4 +290,3 @@ rm phase_list.txt
 rm temp_max*.txt
 rm temp_cols_*.txt
 rm temp_*.txt
-rm TEMP.EPS 
